spring.application.name=rewear
spring.datasource.url=jdbc:mysql://localhost:3306/rewear
spring.datasource.username=root
spring.datasource.password=msqdev0088

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
